### ISSUE TITLE
Remove slack and add Discord server in Readme

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/urlShortner#100]

**Comment by jstiburek** [comment]
Hello Shubhank,
I can resolve this issue if you assign it to me and provide me Discord invite URL :)

Thank you!

**Comment by shubhank-saxena** [comment]
> Hello @shubhank-saxena ,
> I can resolve this issue if you assign it to me and provide me Discord invite URL :)
> 
> Thank you!

Sure @jstiburek Here is the link - dsctiet.xyz/discord
Happy Hacking!

**Comment by shubhank-saxena** [comment]
Not able to assign you this, but consider it assigned!

**Comment by brunoromeiro** [comment]
Would you like to work on this issue?

**Comment by jstiburek** [comment]
@shubhank-saxena 
Task is complete. 
I'm sorry for opening two pull requests I had trouble with squashing commits but I learned from it.
