### ISSUE TITLE
Fix indent in navbar

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/urlShortner#103]
The current navbar doesn't seem to go very well with the layout. Here are the changes that are required 

- DSC TIET logo and name should be shifted to the left side of the container layout
- Toggle switch should be at the right-hand side of the container layout
- URL Shortner as a heading in navbar should be in between both of the above-stated components.

**Comment by StellaJung-Student** [comment]
Hello, I would like to take this issue.

**Comment by atulpandey98** [comment]
Can I work on this issue?
