### ISSUE TITLE
Replace Lorem Ipsem with content

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/urlShortner#104]
We need concrete content here

**Comment by bughunter9** [comment]
@shubhank-saxena  @jsparmani  Can I write the content for this ??

**Comment by shubhank-saxena** [comment]
@bughunter9 I did merge one the PRs which suggested some changes. Feel free to put up a PR if you feel we can have better content!

**Comment by bughunter9** [comment]
On it :)

**Comment by SabhyaGrover** [comment]
Duplicate of #70
