### ISSUE TITLE
Add a Github ribbon on the right top corner of the webpage

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/urlShortner#109]
A side corner ribbon with Github logo, which will redirect to this repo link!

**Comment by ronanren** [comment]
can i assigned to work on this ?

**Comment by ShobhitRathi** [comment]
Hi, you can assign me on this and I'll look into this first thing in the morning

**Comment by shubhank-saxena** [comment]
Sure @ShobhitRathi . Go ahead!

**Comment by ShobhitRathi** [comment]
Also is the website built using html,css?

**Comment by shubhank-saxena** [comment]
This is react based website!
