### ISSUE TITLE
Fix Uncaught (in promise) Error

### ISSUE THREAD

**Issue by saptarshibasu15** [developer-student-club-thapar/urlShortner#116]
### I think that its now the best time to fix this
- Nothing happens when we click on the Shorten button, I wander why.. right then I checked the console window and recognised this error
## Screenshot 👇 (Error message)
![Screenshot (182)](https://user-images.githubusercontent.com/65108480/94993504-25693680-05af-11eb-8c79-bb038d697112.png)
- ### Thereby, by fixing this we further can add a working demo of the application on README.md.

**Comment by SabhyaGrover** [comment]
@saptarshibasu15, it was meant to be designed for organization purposes. Thereby, is not public. You can check the working by cloning it locally and adding routes through [Kutt API](https://docs.kutt.it/) .
