### ISSUE TITLE
Replace Lorem Ipsum with meaningful text

### ISSUE THREAD

**Issue by SabhyaGrover** [developer-student-club-thapar/urlShortner#70]

**Comment by juanbelieni** [comment]
I can work on this

**Comment by shivambhatia5432** [comment]
Is this issue still open?

**Comment by anirbandey303** [comment]
Hey! I've made the changes. If no one is working on this issue you can have a look at my PR.

**Comment by shivambhatia5432** [comment]
Hi I have tried solving the issue without conflicts my pr is #88 do check it :)

**Comment by saptarshibasu15** [comment]
Can I do this.....assign it to me

**Comment by simeon4real** [comment]
is this still open? I will like to work on it.
