### ISSUE TITLE
Dark mode ON state is not retained after refresh

### ISSUE THREAD

**Issue by animesh-007** [developer-student-club-thapar/urlShortner#74]
Dark mode should retain its state after a refresh.

**Comment by aayushmau5** [comment]
@animesh-007 May i work on this one ?

**Comment by animesh-007** [comment]
@aayushmau5 sure!

**Comment by aayushmau5** [comment]
Should i use local storage to store Theme preference ?

**Comment by supanthapaul** [comment]
I've fixed the issue using useEffect and localStorage. Please review the PR and let me know.
#77

**Comment by aayushmau5** [comment]
Hey @animesh-007, i have created the PR. Please check. and let me know, if there is any problem.

**Comment by chandanvishwakarma** [comment]
can you assign to me

**Comment by ryzbaka** [comment]
isn't this better handled by something like useContext?

**Comment by dev348** [comment]
Ok good think your problems solved

**Comment by animesh-007** [comment]
@shubhank-saxena Can you check once this issue is again? It is not resolved yet IMO.

**Comment by akshaikp1** [comment]
> @shubhank-saxena Can you check this issue is again? It is not resolved yet IMO.

problem not solved yet?

**Comment by animesh-007** [comment]
> > @shubhank-saxena Can you check this issue is again? It is not resolved yet IMO.
> 
> problem not solved yet?

No.

**Comment by akshaikp1** [comment]
> > > @shubhank-saxena Can you check this issue is again? It is not resolved yet IMO.
> > 
> > 
> > problem not solved yet?
> 
> No.

can you assign me this task? can i try to do it.
