### ISSUE TITLE
Smallify Atom-Molecule Tab Icon 

### ISSUE THREAD

**Issue by OtoZacpal** [developer-student-club-thapar/urlShortner#84]
Smallify Atom-Molecule icon in tab bar with the DSC logo

**Comment by OtoZacpal** [comment]
Sir,

Kindly smallify Atom-Molecule icon in tab bar with this 
![image](https://user-images.githubusercontent.com/72204658/94811040-77c12080-0412-11eb-952b-a00e27d5c6d2.png)

**Comment by subhashissuara** [comment]
Hey there, can I work on this? If I understand correctly, the default atom icon needs to be replaced by the DSC logo of proper small dimensions.
