### ISSUE TITLE
Page moves slightly whenever the domain dropdown is opened/closed

### ISSUE THREAD

**Issue by ram170** [developer-student-club-thapar/urlShortner#95]
This is happening since overflow-y is hidden whenever the dropdown popup is opened. When the dropdown popup is closed, it is set back to scroll. I assume the position of dropdown popup is fixed/absolute and hence it is done this way. Opening this issue since it is affecting user experience.

**Comment by DivjyotSingh** [comment]
Can I work on this issue? @SabhyaGrover @shubhank-saxena

**Comment by SabhyaGrover** [comment]
@DivjyotSingh sure, go ahead !

**Comment by ram170** [comment]
@DivjyotSingh I have looked at ways to solve this. But it's pretty hard than it seems. This happens due to material UI. Best way to fix this is to not use material UI's MenuItem component. If you're going to do it anyway, there's another way which I did. But it seems like there's a slow change in state and the UI gets pretty glitchy. You can pass these props textField component to disable scroll lock and manually open/close the menuItem component:

`inputProps={{MenuProps: {disableScrollLock: true, open: this.state.isPopupOpen}}}`

But if you do it this way, you have to maintain a state for scroll and pass it as props as I have done above. The state transition is pretty slow and there's a small animation gap in which the UI seems glitchy. Just letting you now since I tried to fix this and came up with this issue. @SabhyaGrover @shubhank-saxena  I'd suggest not to use material UI components to avoid scalability issues like this in future without making much change.

**Comment by shubhank-saxena** [comment]
> @DivjyotSingh I have looked at ways to solve this. But it's pretty hard than it seems. This happens due to material UI. Best way to fix this is to not use material UI's MenuItem component. If you're going to do it anyway, there's another way which I did. But it seems like there's a slow change in state and the UI gets pretty glitchy. You can pass these props to textField component to disable scroll lock and manually open/close the menuItem component:
> 
> `inputProps={{MenuProps: {disableScrollLock: true, open: this.state.isPopupOpen}}}`
> 
> But if you do it this way, you have to maintain a state for scroll and pass it as props as I have done above and close the dropdown popver on scroll. The state transition is pretty slow and there's a small animation gap in which the UI seems glitchy. Just letting you now since I tried to fix this and came up with these issue. @SabhyaGrover @shubhank-saxena I'd suggest not to use material UI components to avoid scalability issues like this in future without making much change.

Oh. I wasn't aware of this. Thank you @ram170 for highlighting this. If the problem persists, @SabhyaGrover we can shift the UI layout framework
