### ISSUE TITLE
Broken UI on mobile

### ISSUE THREAD

**Issue by whoanuragverma** [developer-student-club-thapar/urlShortner#97]

**Comment by shubhank-saxena** [comment]
@whoanuragverma thank you for your interest in this project. Please feel free to fix for the mobile version of it!

**Comment by Samkit-shah** [comment]
I could fix this, please assign it to me @shubhank-saxena

**Comment by shubhank-saxena** [comment]
Okay @Samkit-shah . Go ahead with this!

**Comment by shubhank-saxena** [comment]
@whoanuragverma kindly refrain from closing this issue. It's not solved yet!
