### ISSUE TITLE
Header is transparent

### ISSUE THREAD

**Issue by KodingNYoung** [developer-student-club-thapar/urlShortner#99]
The header is transparent and messes up the text in the page when the page is scrolled down..

I've attached a screenshot of the bug.. 
![Screenshot (149)](https://user-images.githubusercontent.com/58640839/94928295-62ec9780-04bb-11eb-8b70-b200c6712ce4.png)

I've fixed it and it looks like this...
![Screenshot (150)](https://user-images.githubusercontent.com/58640839/94928509-b2cb5e80-04bb-11eb-9328-5c37d6784ea3.png)

May I create a PR?

**Comment by KodingNYoung** [comment]
@jsparmani ??

**Comment by ram170** [comment]
I have fixed this as a part of #82

**Comment by KodingNYoung** [comment]
okay

**Comment by shubhank-saxena** [comment]
Thank you @KodingNYoung . I think @ram170 has already solved this issue. Feel free to check other issues as we have quite a few of them open
